apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app-container
        image: gcr.io/plenary-utility-438302-m7/go-app:v1  # Asegúrate de que esta imagen sea la correcta
        ports:
        - containerPort: 8080
