apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-losers
  labels:
    app: consumer-losers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer-losers
  template:
    metadata:
      labels:
        app: consumer-losers
    spec:
      containers:
      - name: consumer-losers
        image: gcr.io/your-project-id/consumer-losers:latest
        env:
        - name: KAFKA_BROKER
          value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
        - name: REDIS_HOST
          value: "redis"
        - name: KAFKA_TOPIC
          value: "losers"
        ports:
        - containerPort: 8080
