apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-service
  labels:
    app: faculty-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faculty-service
  template:
    metadata:
      labels:
        app: faculty-service
    spec:
      containers:
      - name: faculty-service
        image: gcr.io/your-project-id/faculty-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-service
spec:
  selector:
    app: faculty-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
