apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxing-service
  labels:
    app: boxing-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: boxing-service
  template:
    metadata:
      labels:
        app: boxing-service
    spec:
      containers:
      - name: boxing-service
        image: gcr.io/plenary-utility-438302-m7/boxing-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: GCP_PROJECT_ID
          value: "plenary-utility-438302-m7"
        - name: KAFKA_BROKER
          value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
        - name: KAFKA_TOPIC_WINNERS
          value: "winners"
        - name: KAFKA_TOPIC_LOSERS
          value: "losers"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: BOXING_SERVICE_PORT
          value: "8083"

---
apiVersion: v1
kind: Service
metadata:
  name: boxing-service
spec:
  selector:
    app: boxing-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083
  type: ClusterIP
