apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-service
  labels:
    app: faculty-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: faculty-service
  template:
    metadata:
      labels:
        app: faculty-service
    spec:
      containers:
      - name: faculty-service
        image: gcr.io/plenary-utility-438302-m7/faculty-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: GCP_PROJECT_ID
          value: "plenary-utility-438302-m7"
        - name: KAFKA_BROKER
          value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: FACULTY_SERVICE_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-service
spec:
  selector:
    app: faculty-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
