apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-service-rust
  labels:
    app: faculty-service-rust
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faculty-service-rust
  template:
    metadata:
      labels:
        app: faculty-service-rust
    spec:
      containers:
      - name: faculty-service-rust
        image: gcr.io/plenary-utility-438302-m7/faculty-service-rust:latest
        ports:
        - containerPort: 8084
        env:
        - name: GCP_PROJECT_ID
          value: "plenary-utility-438302-m7"
        - name: KAFKA_BROKER
          value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: FACULTY_SERVICE_RUST_PORT
          value: "8084"
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-service-rust
spec:
  selector:
    app: faculty-service-rust
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8084
  type: LoadBalancer
