apiVersion: apps/v1
kind: Deployment
metadata:
  name: swimming-service
  labels:
    app: swimming-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swimming-service
  template:
    metadata:
      labels:
        app: swimming-service
    spec:
      containers:
      - name: swimming-service
        image: gcr.io/plenary-utility-438302-m7/discipline-swimming:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: swimming-service
spec:
  selector:
    app: swimming-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: ClusterIP
