apiVersion: apps/v1
kind: Deployment
metadata:
  name: track-service
  labels:
    app: track-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: track-service
  template:
    metadata:
      labels:
        app: track-service
    spec:
      containers:
      - name: track-service
        image: gcr.io/plenary-utility-438302-m7/discipline-track:latest
        ports:
        - containerPort: 8082
        env:
        - name: KAFKA_BROKER
          value: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"  # URL del broker de Kafka
---
apiVersion: v1
kind: Service
metadata:
  name: track-service
spec:
  selector:
    app: track-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
  type: ClusterIP
